### ISSUE TITLE
Implementation examples?

### ISSUE THREAD

**Issue by ajbdev** [Blizzard/heroprotocol#1]
I'm keen to see where this goes or what it's used for - are you willing to share any example implementation code or projects that use this?

Thanks for open sourcing this!

**Comment by tenarsis** [comment]
You can use this script as-is to dump the contents of any existing .StormReplay file as JSON.

Example command line: heroprotocol.py --details "Blackheart's Bay.StormReplay" > blackheart.txt
This lists all players in the game and which hero was picked, along with a lot of other data.

--details is just one supported option, you can run it with --help to see all supported outputs.

In the future we may upload some examples like a batch replay data aggregation script, but that should be a pretty simple extension to what already exists.

**Comment by riklaunim** [comment]
Python! nice. I'll see if I can make any meaningful tutorial out of it :)

**Comment by sanjabonic** [comment]
It's just great and easy to use - thanks for doing this and we're already working on a nice project using it. ;) Working soon™. I don't think much of a tutorial is needed since it's really just heroprotocol.py --option "replayname". But there's so much information to extract and then do amazing stuff with it!

**Comment by riklaunim** [comment]
I'm thinking about some PyQt5 example simple app or some database data usage.

**Comment by crorella** [comment]
You can check one implementation here: https://github.com/crorella/hots-parser
