### ISSUE TITLE
How to determine two replay files are the same game？

### ISSUE THREAD

**Issue by JanSword** [Blizzard/heroprotocol#66]
I think each game should has an only key，but how can I get this？
Thank you！

**Comment by healingbrew** [comment]
What I do is compare the map, team compositions (ordered by name), and the lobby seed (it's in init data, `initData.m_syncLobbyState.m_gameDescription.m_randomValue`).

**Comment by mikeeheler** [comment]
Hi @JanSword, as far as I'm aware, there isn't a uniquely-identifying ID available for a single game that is saved with all replay files of the same game. However, using the code linked by @healingbrew is a good idea since it will be compatible with HotsApi and HotsLogs and it should be unique enough for all intents and purposes.

Effectively:

- Take m_toon.m_id for every player in details.m_playerList, sorted numerically and concatenated into a single string with initdata.m_syncLobbyState.m_gameDescription.m_randomValue at the end.
- Get the MD5 hash of that string as bytes (not as a string i.e. '92959a96fd69146c5fe7cbde6e5720f2' but rather as the bytes [0x92, 0x95, 0x9a, ..., 0x20, 0xf2].
- Convert that MD5 hash to a GUID using their specific algorithm.
