### ISSUE TITLE
Unsupported base build: 86223

### ISSUE THREAD

**Issue by qcasey** [Blizzard/heroprotocol#98]
Hi, I'm trying to run this on some of my recent replays and am getting this error. It works OK with games from October

```Unsupported base build: 86223```

**Comment by gmelodie** [comment]
For future reference, these errors `Unsupported base build: XXXXX` are generally due to an outdated version of the `heroprotocol` package. Update it either by recloning the repo and reinstalling the package or by `pip install --upgrade heroprotocol`, but that last method may fail if the new build is not yet on PyPi.

**Comment by qcasey** [comment]
Thank you, that did indeed work.
